<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Rust真难啊</title>
</head>
<body>
<p><a href="https://zhuanlan.zhihu.com/p/27438530">原文</a></p>
<p>最近Rust社区又发现了一个隐藏得很深的违反了“内存安全”的bug。Bug描述见此处：<a href="https://github.com/rust-lang/rust/issues/41622" data-editable="true" data-title="MutexGuard&lt;Cell&lt;i32&gt;&gt; must not be Sync · Issue #41622 · rust-lang/rust">MutexGuard&lt;Cell&lt;i32&gt;&gt; must not be Sync · Issue #41622 · rust-lang/rust</a>。</p><p>这个问题是这样的，观察这样的一段程序：</p><code lang="text">use std::sync::Mutex;
use std::cell::Cell;

extern crate rayon;

fn main()
{
    let m = Mutex::new(Cell::new(0));
    let g = m.lock().unwrap();
    {
        rayon::join(
            || { g.set(g.get() + 1); println!("Thread 1: {:?}", g.get()) },
            || { g.set(g.get() + 1); println!("Thread 2: {:?}", g.get()) });
    }
}

</code><p>这里用到了 <a href="https://github.com/nikomatsakis/rayon" data-editable="true" data-title="rayon">rayon</a> 这个库，来实现并行执行的功能。join 函数接受了两个参数，分别是两个闭包，rayon会自动将它们分配到线程池中，选择合适的线程来执行它们。问题是，在这俩闭包访问了共享变量g，而它们俩内部，根本没有做任何线程同步。也就是说，这里有线程不安全的情况。</p><p>如果大家还没理解是什么意思，我们再用以前经常使用的一个示例来演示，两个线程修改同一个变量：</p><code lang="text">extern crate scoped_threadpool;
use scoped_threadpool::Pool;
use std::sync::Mutex;
use std::cell::Cell;

const COUNT: u32 = 1000000;

fn main() {
    // Create a threadpool holding 4 threads
    let mut pool = Pool::new(4);

    let m = Mutex::new(Cell::new(0_i64));
    let g = m.lock().unwrap();

    pool.scoped(|scoped| {
        let g1 = &amp;g;
        scoped.execute(move ||{
            for _ in 0..COUNT {
                g1.set(g1.get() + 1);
            }
        });
        let g2 = &amp;g;
        scoped.execute(move ||{
            for _ in 0..COUNT {
                g2.set(g2.get() - 1);
            }
        });
    });

    println!("{}", g.get());
}

</code><p>用目前的稳定版编译，没问题：</p><code lang="text">rustc -V
rustc 1.18.0 (03fc9d622 2017-06-06)

</code><p>但是，执行起来就会发现，这个变量的值最终没有回到0，每次执行结果都不一样。这说明两个线程之间确实没有做好同步。按照 rust 给我们的保证，只要我们自己不乱用 unsafe，“内存不安全”和“线程不安全”的代码就根本不应该编译通过。可惜的是，我们还是发现了这样的安全漏洞。</p><p>用目前最新的 nightly 版本编译，发现编译错误：</p><code lang="text">error[E0277]: the trait bound `std::cell::Cell&lt;i64&gt;: std::marker::Sync` is not satisfied

</code><p>因为这个 bug 在最新的 nightly 版本上修复了，编译器正确地拒绝了这段代码编译通过。</p><h2>原因分析</h2><p>join 函数的签名是这样的：</p><code lang="text">pub fn join&lt;A, B, RA, RB&gt;(oper_a: A, oper_b: B) -&gt; (RA, RB)
where
    A: FnOnce() -&gt; RA + Send,
    B: FnOnce() -&gt; RB + Send,
    RA: Send,
    RB: Send,

</code><p>execute 函数的签名是这样的：</p><code lang="text">fn execute&lt;F&gt;(&amp;self, f: F)
where
    F: FnOnce() + Send + 'scope,

</code><p>它们都要求闭包参数满足 Send 约束。按照 Send 的定义，这是非常合理的条件。如果一个类型满足 Send，那么把它 move 到其它线程中一定是安全的。所以，rayon 或者 scoped_threadpool 这两个库的设计是没什么问题的。那么bug的原因只剩下一种可能性：我们把不该标记为 Send 的类型给错误地标成了 Send。</p><p>这个错误出现在 MutexGuard&lt;T&gt; 这个类型上。它是 Mutex&lt;T&gt; 类型调用 lock() 方法后返回的类型，它实现了</p><p>impl Deref for MutexGuard&lt;T&gt; { type Target = t; }</p><p>所以它可以直接调用 T 类型的方法，而且它有一个析构函数，当它销毁的时候，会自动调用 unlock() 方法。这个类型是一个很方便的工具类，很多时候我们都不需要注意它的存在。</p><p>那么，以前的编译器犯了什么错误，导致了这个bug发生呢？</p><h2>auto trait</h2><p>这里的关键是 auto trait。这个概念以前也叫 OIBIT, 全称<a href="https://github.com/rust-lang/rfcs/blob/master/text/0019-opt-in-builtin-traits.md" data-editable="true" data-title="opt-in builtin traits">opt-in builtin traits</a>。 (请不要深究这个概念为毛起了这样一个又臭又长的名字，所有人都不喜欢这个名字，后来大家都改为称作 auto trait )</p><p>对于某些特殊的 trait，编译器允许用户不用手写 impl，自动根据这个类型的成员“推理”出来这个类型是否满足这个 trait。所谓的特殊trait，指的是使用了如下特殊语法的trait：</p><code lang="text">unsafe impl Send for .. { }
unsafe impl Sync for .. { }

</code><p>如果一个 trait 用了这样的语法，那它就是auto trait。Send 和 Sync 都是 auto trait。如果一个类型没用明确的 impl Send/Sync，编译器就会根据它的成员来推理它是否满足 Send/Sync。如果所有成员都是 Send/Sync，那它就满足 Send/Sync，否则就不是。</p><p>比如对于闭包类型，每个闭包都是一个单独的匿名结构体类型，这个闭包是否满足 Send/Sync，就要看它捕获的变量是否满足 Send/Sync。</p><p>对于最开始的那个例子，编译器的推理过程是这样的：</p><ol><li>join 方法要求参数要满足 Send 约束，那么就需要检查传进来的这两个闭包是否满足 Send 约束。</li><li>这俩闭包都只捕获了一个变量 &amp;g (注意这里又用到了闭包捕获规则，因为闭包体内只用到了 g 的共享引用，因此捕获的时候不会发生move，只会借用)。根据 auto trait 规则，因此需要检查成员变量 &amp;g 的类型是否满足 Send。</li><li>标准库中有<a href="https://doc.rust-lang.org/src/core/marker.rs.html#553" data-editable="true" data-title="这样一个定义">这样一个定义</a>：<code lang="text">unsafe impl&lt;'a, T: Sync + ?Sized&gt; Send for &amp;'a T {}

</code>即，如果 T 满足 Sync，则 &amp;T 满足 Send。所以，编译器需要检查 g 是否满足 Sync。</li><li>标准库中只有这么一句话：<code lang="text">impl&lt;'a, T: ?Sized&gt; !marker::Send for MutexGuard&lt;'a, T&gt; {}

</code>这说明 MutexGuard 不是 Send，而没找到关于 Sync 的impl。根据 auto trait 规则，需要继续检查它的每个成员是否满足 Sync。</li><li>MutexGuard 的定义如下：<code lang="text">pub struct MutexGuard&lt;'a, T: ?Sized + 'a&gt; {
    __lock: &amp;'a Mutex&lt;T&gt;,
    __poison: poison::Guard,
}

</code>继续检查它的每个成员是否满足 Sync。</li><li>对于成员 __poison, 这个类型只有一个成员：<code lang="text">pub struct Guard {
    panicking: bool,
}

</code>因为bool类型满足 Sync，所以 Guard 满足 Sync。</li><li>对于成员 __lock，根据 Sync 的定义，只要 Mutex&lt;T&gt; 满足 Sync，则 &amp;Mutex&lt;T&gt; 满足Sync。继续检查 Mutex&lt;T&gt; 是否满足 Sync。</li><li>根据标准库中 Mutex&lt;T&gt; 的定义：<code lang="text">unsafe impl&lt;T: ?Sized + Send&gt; Send for Mutex&lt;T&gt; { }
unsafe impl&lt;T: ?Sized + Send&gt; Sync for Mutex&lt;T&gt; { }

</code>即只要 T 满足 Send，则 Mutex&lt;T&gt; 满足 Sync。</li><li>此处我们的类型T参数实际上是 Cell&lt;i32&gt;，最后判断 Cell&lt;i32&gt; 是否满足 Send：<code lang="text">unsafe impl&lt;T&gt; Send for Cell&lt;T&gt; where T: Send {}

</code>即，只要 T 满足 Send，则 Cell&lt;T&gt; 满足 Send。此处 i32 类型是满足的，推理完毕。</li></ol><h2>修复方案</h2><p>知道了这个bug产生的原因，修复就很简单了，我们只需要对 MutexGuard 手工实现一下 impl 不要利用 auto trait 的自动推理机制即可：</p><code lang="text">unsafe impl&lt;'a, T: ?Sized + Sync&gt; Sync for MutexGuard&lt;'a, T&gt; { }

</code><p>除此之外，这个 bug 也提醒我们，auto trait 的设计并不完美，它本该在一开始就不应该对 MutexGuard 这样的类型“自动” impl Sync。关于这方面的进一步的讨论，可以参见： <a href="https://internals.rust-lang.org/t/unsafe-types-and-auto-traits/5385" data-editable="true" data-title="Unsafe types and auto traits">Unsafe types and auto traits</a> <a href="https://internals.rust-lang.org/t/changing-the-impl-trait-for-syntax/3891" data-editable="true" data-title="Changing the `impl Trait for .. { }` syntax">Changing the `impl Trait for .. { }` syntax</a></p><p>这是一个Rust特有的bug。在C/C++中是不存在这样的问题的。在C/C++中，没有哪个库会给用户提供“内存安全”或者“线程安全”之类的保证，所有这些问题是靠文档来保证的，编译器或者静态检查工具永远只能检查出其中一小部分问题。用户可以轻松触发此类问题，而编译器和标准库的作者不必对此负责。Rust做出了这样的保证，编译器和标准库的作者身上的责任要远大于C/C++中的同等角色。</p><p>同时，这也提醒我们，以Rust的代码质量标准，写出完全正确的 unsafe 代码是多么困难的一件事情。</p><p>这个bug之所以这么久都没人发现，主要是由于这样的写法在实践中没人真正这么用，因此它的实际影响很小。这个bug的发现者是一个专门研究编程语言的专家，他正在做的一个研究项目是<a href="https://www.ralfj.de/blog/2015/10/12/formalizing-rust.html" data-editable="true" data-title="Rust类型系统形式化">Rust类型系统形式化</a>。本文也是参考他的这篇博客写成：<a href="https://www.ralfj.de/blog/2017/06/09/mutexguard-sync.html" data-editable="true" data-title="How MutexGuard was Sync When It Should Not Have Been">How MutexGuard was Sync When It Should Not Have Been</a>。</p>
<script async defer="defer" src="https://www.googletagmanager.com/gtag/js?id=UA-7909075-5"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){ dataLayer.push(arguments); }
gtag('js', new Date());
gtag('config', 'UA-7909075-5');
</script>
<script>
var _hmt = _hmt || [];
</script>
<script async defer="defer" src="https://hm.baidu.com/hm.js?e3d40295e416616ddc21287da9646d31"></script>
</body>
</html>
