<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>TiKV 源码解析系列文章（五）fail-rs 介绍</title>
</head>
<body>
<p><a href="https://zhuanlan.zhihu.com/p/60828896">原文</a></p>
<div class="title-image"><img src="https://pic2.zhimg.com/v2-25202dccab23cfd715153fc1377b1045_b.jpg" alt=""></div><p>作者：张博康</p><p>本文为 TiKV 源码解析系列的第五篇，为大家介绍 TiKV 在测试中使用的周边库 <a href="http://link.zhihu.com/?target=https%3A//github.com/pingcap/fail-rs" class=" wrap external" target="_blank" rel="nofollow noreferrer">fail-rs</a>。</p><p>fail-rs 的设计启发于 FreeBSD 的 <a href="http://link.zhihu.com/?target=https%3A//www.freebsd.org/cgi/man.cgi%3Fquery%3Dfail" class=" wrap external" target="_blank" rel="nofollow noreferrer">failpoints</a>，由 Rust 实现。通过代码或者环境变量，其允许程序在特定的地方动态地注入错误或者其他行为。在 TiKV 中通常在测试中使用 fail point 来构建异常的情况，是一个非常方便的测试工具。</p><h2>Fail point 需求</h2><p>在我们的集成测试中，都是简单的构建一个 KV 实例，然后发送请求，检查返回值和状态的改变。这样的测试可以较为完整地测试功能，但是对于一些需要精细化控制的测试就鞭长莫及了。我们当然可以通过 mock 网络层提供网络的精细模拟控制，但是对于诸如磁盘 IO、系统调度等方面的控制就没办法做到了。</p><p>同时，在分布式系统中时序的关系是非常关键的，可能两个操作的执行顺行相反，就导致了迥然不同的结果。尤其对于数据库来说，保证数据的一致性是至关重要的，因此需要去做一些相关的测试。</p><p>基于以上原因，我们就需要使用 fail point 来复现一些 corner case，比如模拟数据落盘特别慢、raftstore 繁忙、特殊的操作处理顺序、错误 panic 等等。</p><h2>基本用法</h2><h3>示例</h3><p>在详细介绍之前，先举一个简单的例子给大家一个直观的认识。</p><p>还是那个老生常谈的 Hello World：</p><div class="highlight"><pre><code class="language-text"><span></span>#[macro_use]
extern crate fail;

fn say_hello() {
    fail_point!(“before_print”);
    println!(“Hello World~”);
}

fn main() {
    say_hello();
    fail::cfg("before_print", "panic");
    say_hello();
}
</code></pre></div><p>运行结果如下：</p><div class="highlight"><pre><code class="language-text"><span></span>Hello World~
thread 'main' panicked at 'failpoint before_print panic' ...
</code></pre></div><p>可以看到最终只打印出一个 <code>Hello World～</code>，而在打印第二个之前就 panic 了。这是因为我们在第一次打印完后才指定了这个 fail point 行为是 panic，因此第一次在 fail point 不做任何事情之后正常输出，而第二次在执行到 fail point 时就会根据配置的行为 panic 掉！</p><h3>Fail point 行为</h3><p>当然 fail point 不仅仅能注入 panic，还可以是其他的操作，并且可以按照一定的概率出现。描述行为的格式如下：</p><div class="highlight"><pre><code class="language-text"><span></span>[&lt;pct&gt;%][&lt;cnt&gt;*]&lt;type&gt;[(args...)][-&gt;&lt;more terms&gt;]
</code></pre></div><ul><li>pct：行为被执行时有百分之 pct 的机率触发</li><li>cnt：行为总共能被触发的次数</li><li>type：行为类型</li><ul><li>off：不做任何事</li><li>return(arg)：提前返回，需要 fail point 定义时指定 expr，arg 会作为字符串传给 expr 计算返回值</li><li>sleep(arg)：使当前线程睡眠 arg 毫秒</li><li>panic(arg)：使当前线程崩溃，崩溃消息为 arg</li><li>print(arg)：打印出 arg</li><li>pause：暂停当前线程，直到该 fail point 设置为其他行为为止</li><li>yield：使当前线程放弃剩余时间片</li><li>delay(arg)：和 sleep 类似，但是让 CPU 空转 arg 毫秒</li></ul><li>args：行为的参数</li></ul><p>比如我们想在 <code>before_print</code> 处先 sleep 1s 然后有 1% 的机率 panic，那么就可以这么写：</p><div class="highlight"><pre><code class="language-text"><span></span>"sleep(1000)-&gt;1%panic"
</code></pre></div><h3>定义 fail point</h3><p>只需要使用宏 <code>fail_point!</code> 就可以在相应代码中提前定义好 fail point，而具体的行为在之后动态注入。</p><div class="highlight"><pre><code class="language-text"><span></span>fail_point!("failpoint_name");
fail_point!("failpoint_name", |_| { // 指定生成自定义返回值的闭包，只有当 fail point 的行为为 return 时，才会调用该闭包并返回结果
    return Error
});
fail_point!("failpoint_name", a == b, |_| { // 当满足条件时，fail point 才被触发
    return Error
})
</code></pre></div><h3>动态注入</h3><p><b>环境变量</b></p><p>通过设置环境变量指定相应 fail point 的行为：</p><div class="highlight"><pre><code class="language-text"><span></span>FAILPOINTS="&lt;failpoint_name1&gt;=&lt;action&gt;;&lt;failpoint_name2&gt;=&lt;action&gt;;..."
</code></pre></div><p>注意，在实际运行的代码需要先使用 <code>fail::setup()</code> 以环境变量去设置相应 fail point，否则 <code>FAILPOINTS</code> 并不会起作用。</p><div class="highlight"><pre><code class="language-text"><span></span>#[macro_use]
extern crate fail;

fn main() {
    fail::setup(); // 初始化 fail point 设置
    do_fallible_work();
    fail::teardown(); // 清除所有 fail point 设置，并且恢复所有被 fail point 暂停的线程
}
</code></pre></div><p><b>代码控制</b></p><p>不同于环境变量方式，代码控制更加灵活，可以在程序中根据情况动态调整 fail point 的行为。这种方式主要应用于集成测试，以此可以很轻松地构建出各种异常情况。</p><div class="highlight"><pre><code class="language-text"><span></span>fail::cfg("failpoint_name", "actions"); // 设置相应的 fail point 的行为
fail::remove("failpoint_name"); // 解除相应的 fail point 的行为
</code></pre></div><h2>内部实现</h2><p>以下我们将以 fail-rs v0.2.1 版本代码为基础，从 API 出发来看看其背后的具体实现。</p><p>fail-rs 的实现非常简单，总的来说，就是内部维护了一个全局 map，其保存着相应 fail point 所对应的行为。当程序执行到某个 fail point 时，获取并执行该全局 map 中所保存的相应的行为。</p><p>全局 map 其具体定义在 <a href="http://link.zhihu.com/?target=https%3A//github.com/pingcap/fail-rs/blob/v0.2.1/src/lib.rs%23L602" class=" wrap external" target="_blank" rel="nofollow noreferrer">FailPointRegistry</a>。</p><div class="highlight"><pre><code class="language-text"><span></span>struct FailPointRegistry {
    registry: RwLock&lt;HashMap&lt;String, Arc&lt;FailPoint&gt;&gt;&gt;,
}
</code></pre></div><p>其中 <a href="http://link.zhihu.com/?target=https%3A//github.com/pingcap/fail-rs/blob/v0.2.1/src/lib.rs%23L518" class=" wrap external" target="_blank" rel="nofollow noreferrer">FailPoint</a> 的定义如下：</p><div class="highlight"><pre><code class="language-text"><span></span>struct FailPoint {
    pause: Mutex&lt;bool&gt;,
    pause_notifier: Condvar,
    actions: RwLock&lt;Vec&lt;Action&gt;&gt;,
    actions_str: RwLock&lt;String&gt;,
}
</code></pre></div><p><code>pause</code> 和 <code>pause_notifier</code> 是用于实现线程的暂停和恢复，感兴趣的同学可以去看看代码，太过细节在此不展开了；<code>actions_str</code> 保存着描述行为的字符串，用于输出；而 <code>actions</code> 就是保存着 failpoint 的行为，包括概率、次数、以及具体行为。<code>Action</code> 实现了 <code>FromStr</code> 的 trait，可以将满足格式要求的字符串转换成 <code>Action</code>。这样各个 API 的操作也就显而易见了，实际上就是对于这个全局 map 的增删查改：</p><ul><li><a href="http://link.zhihu.com/?target=https%3A//github.com/pingcap/fail-rs/blob/v0.2.1/src/lib.rs%23L628" class=" wrap external" target="_blank" rel="nofollow noreferrer">fail::setup()</a> 读取环境变量 <code>FAILPOINTS</code> 的值，以 <code>;</code> 分割，解析出多个 <code>failpoint name</code> 和相应的 <code>actions</code> 并保存在 <code>registry</code> 中。</li><li><a href="http://link.zhihu.com/?target=https%3A//github.com/pingcap/fail-rs/blob/v0.2.1/src/lib.rs%23L729" class=" wrap external" target="_blank" rel="nofollow noreferrer">fail::teardown()</a> 设置 <code>registry</code> 中所有 fail point 对应的 <code>actions</code> 为空。</li><li><a href="http://link.zhihu.com/?target=https%3A//github.com/pingcap/fail-rs/blob/v0.2.1/src/lib.rs%23L729" class=" wrap external" target="_blank" rel="nofollow noreferrer">fail::cfg(name, actions)</a> 将 <code>name</code> 和对应解析出的 <code>actions</code> 保存在 <code>registry</code> 中。</li><li><a href="http://link.zhihu.com/?target=https%3A//github.com/pingcap/fail-rs/blob/v0.2.1/src/lib.rs%23L729" class=" wrap external" target="_blank" rel="nofollow noreferrer">fail::remove(name)</a> 设置 <code>registry</code> 中 <code>name</code> 对应的 <code>actions</code> 为空。</li></ul><p>而代码到执行到 fail point 的时候到底发生了什么呢，我们可以展开 <a href="http://link.zhihu.com/?target=https%3A//github.com/pingcap/fail-rs/blob/v0.2.1/src/lib.rs%23L817" class=" wrap external" target="_blank" rel="nofollow noreferrer">fail_point!</a> 宏定义看一下：</p><div class="highlight"><pre><code class="language-text"><span></span>macro_rules! fail_point {
    ($name:expr) =&gt; {{
        $crate::eval($name, |_| {
            panic!("Return is not supported for the fail point \"{}\"", $name);
        });
    }};
    ($name:expr, $e:expr) =&gt; {{
        if let Some(res) = $crate::eval($name, $e) {
            return res;
        }
    }};
    ($name:expr, $cond:expr, $e:expr) =&gt; {{
        if $cond {
            fail_point!($name, $e);
        }
    }};
}
</code></pre></div><p>现在一切都变得豁然开朗了，实际上就是对于 <code>eval</code> 函数的调用，当函数返回值为 <code>Some</code> 时则提前返回。而 <code>eval</code> 就是从全局 map 中获取相应的行为，在 <code>p.eval(name)</code> 中执行相应的动作，比如输出、等待亦或者 panic。而对于 <code>return</code> 行为的情况会特殊一些，在 <code>p.eval(name)</code> 中并不做实际的动作，而是返回 <code>Some(arg)</code> 并通过 <code>.map(f)</code> 传参给闭包产生自定义的返回值。</p><div class="highlight"><pre><code class="language-text"><span></span>pub fn eval&lt;R, F: FnOnce(Option&lt;String&gt;) -&gt; R&gt;(name: &amp;str, f: F) -&gt; Option&lt;R&gt; {
    let p = {
        let registry = REGISTRY.registry.read().unwrap();
        match registry.get(name) {
            None =&gt; return None,
            Some(p) =&gt; p.clone(),
        }
    };
    p.eval(name).map(f)
}
</code></pre></div><h2>小结</h2><p>至此，关于 fail-rs 背后的秘密也就清清楚楚了。关于在 TiKV 中使用 fail point 的测试详见 <a href="http://link.zhihu.com/?target=https%3A//github.com/tikv/tikv/tree/master/tests/failpoints" class=" wrap external" target="_blank" rel="nofollow noreferrer">github.com/tikv/tikv/tree/master/tests/failpoints</a>，大家感兴趣可以看看在 TiKV 中是如何来构建异常情况的。</p><p>同时，fail-rs 计划支持 HTTP API，欢迎感兴趣的小伙伴提交 PR。</p><p><b>更多阅读：</b></p><a href="http://link.zhihu.com/?target=https%3A//www.pingcap.com/blog-cn/%23TiKV-%25E6%25BA%2590%25E7%25A0%2581%25E8%25A7%25A3%25E6%259E%2590" data-draft-node="block" data-draft-type="link-card" data-image="https://pic2.zhimg.com/v2-60ab5bd867c2434d70c957a02a2169e1_ipico.jpg" data-image-width="1200" data-image-height="1200" class=" wrap external" target="_blank" rel="nofollow noreferrer">博客</a><p></p>
<script async defer="defer" src="https://www.googletagmanager.com/gtag/js?id=UA-7909075-5"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){ dataLayer.push(arguments); }
gtag('js', new Date());
gtag('config', 'UA-7909075-5');
</script>
<script>
var _hmt = _hmt || [];
</script>
<script async defer="defer" src="https://hm.baidu.com/hm.js?e3d40295e416616ddc21287da9646d31"></script>
</body>
</html>
